import type { MissionDef } from './types';

/** Sturmschaden: Baum liegt quer auf der Landstraße, PKW wartet davor. */
export const STORM_TREE: MissionDef = {
  id: 'storm-tree',
  title: 'Sturmschaden: Baum auf der Straße',
  background: 'storm-tree-bg',
  groundY: 304,
  vehicleHotspot: 'vehicle',
  vehiclePos: { x: 414, y: 320 },
  entryTask: 'exit',
  parTimeMs: 240000,
  reinforcementText: 'Nachalarmierung: zurück zur Unterkunft, GKW holen, wieder anfahren. Die Zeit läuft weiter.',
  hotspots: [
    { id: 'vehicle', label: 'Einsatzfahrzeug', x: 412, y: 208, w: 228, h: 116, walkX: 400, idleText: 'Das Fahrzeug steht sicher am Bankett.' },
    { id: 'car', label: 'Wartender PKW', x: 32, y: 236, w: 120, h: 64, walkX: 160, idleText: 'Der Fahrer hört Radio.' },
    { id: 'tree', label: 'Umgestürzter Baum', x: 172, y: 212, w: 196, h: 84, walkX: 300, idleText: 'Der Stamm liegt quer. Ohne Säge bewegt sich hier nichts.' },
    { id: 'log1', label: 'Stammteil', x: 212, y: 256, w: 60, h: 32, walkX: 242 },
    { id: 'log2', label: 'Stammteil', x: 280, y: 256, w: 60, h: 32, walkX: 310 },
    { id: 'log3', label: 'Stammteil', x: 348, y: 256, w: 60, h: 32, walkX: 378 },
    { id: 'road-left', label: 'Straße, linke Seite', x: 0, y: 240, w: 32, h: 88, walkX: 28, idleText: 'Freie Sicht bis zur Kurve.' },
    { id: 'road-right', label: 'Straße, rechte Seite', x: 370, y: 240, w: 40, h: 88, walkX: 388, idleText: 'Hinter dem Fahrzeug kommt die Kuppe.' },
  ],
  props: [
    { id: 'car', x: 40, y: 260, w: 100, h: 36, color: 'red', label: 'PKW' },
    { id: 'car-blinker', x: 132, y: 268, w: 8, h: 6, color: 'orange' },
    { id: 'crown', x: 168, y: 216, w: 60, h: 80, color: 'green' },
    { id: 'trunk', x: 208, y: 252, w: 200, h: 28, color: 'brown' },
    { id: 'log1', x: 216, y: 264, w: 52, h: 24, color: 'brownLight', hidden: true },
    { id: 'log2', x: 284, y: 264, w: 52, h: 24, color: 'brownLight', hidden: true },
    { id: 'log3', x: 352, y: 264, w: 52, h: 24, color: 'brownLight', hidden: true },
    { id: 'triangle-left', x: 4, y: 280, w: 16, h: 16, color: 'red', hidden: true },
    { id: 'cone-left', x: 20, y: 292, w: 10, h: 16, color: 'orange', hidden: true },
    { id: 'cone-right', x: 386, y: 292, w: 10, h: 16, color: 'orange', hidden: true },
  ],
  tasks: [
    {
      id: 'exit',
      label: 'Aussteigen',
      hotspot: 'vehicle',
      resetOnReturn: true,
      choice: {
        prompt: 'Du sitzt im Fahrzeug. Auf der Landstraße rauscht der Verkehr vorbei.',
        options: [
          { label: 'Verkehr beobachten, dann aussteigen', outcome: 'ok', text: 'Du wartest, bis frei ist, und steigst zur Bankettseite aus.' },
          { label: 'Einfach aussteigen', outcome: 'gameover', text: 'Du bist gestorben, weil du falsch aus dem Auto ausgestiegen bist.' },
        ],
      },
      durationMs: 600,
    },
    {
      id: 'talk-driver',
      label: 'Mit dem Fahrer sprechen',
      hotspot: 'car',
      optional: true,
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Der Fahrer ist unverletzt und bleibt im Auto. Er wollte nur Brötchen holen.',
    },
    {
      id: 'get-barrier',
      label: 'Absperrmaterial holen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['barrier'],
      durationMs: 1500,
      doneText: 'Warndreieck und vier Leitkegel. Reicht für beide Seiten.',
    },
    {
      id: 'barrier-left',
      label: 'Absperrung aufstellen',
      hotspot: 'road-left',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-left', 'triangle-left'],
    },
    {
      id: 'barrier-right',
      label: 'Absperrung aufstellen',
      hotspot: 'road-right',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-right'],
    },
    {
      id: 'ppe',
      label: 'Schnittschutz-PSA anlegen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['ppe'],
      missingEquipmentText: 'Im MTW liegt keine Schnittschutzhose und keine Säge. Der GKW hat beides. Also: absperren, zurück, GKW holen.',
      durationMs: 2000,
      doneText: 'Schnittschutzhose, Helm mit Visier, Gehörschutz. Sitzt.',
    },
    {
      id: 'cut-tree',
      label: 'Baum zerlegen',
      hotspot: 'tree',
      requires: ['exit'],
      equipment: ['chainsaw'],
      missingEquipmentText: 'Keine Kettensäge im MTW. Du kannst absperren, den Baum kriegst du so nicht klein. GKW nachalarmieren.',
      safety: [{ missing: 'ppe', gameOver: 'Du bist gestorben, weil du die Kettensäge ohne Schnittschutz gestartet hast.' }],
      softOrder: [
        { missing: 'barrier-left', penaltyMs: 30000, text: 'Ohne Absperrung rauscht ein Auto an dir vorbei und hupt. Du brichst ab und atmest durch. (+30 s)' },
        { missing: 'barrier-right', penaltyMs: 30000, text: 'Von rechts kommt ein Traktor bis auf zwei Meter ran. Ohne Absperrung ist das nichts. (+30 s)' },
      ],
      usesEquipment: ['chainsaw'],
      minigame: {
        prompt: 'Der Stamm liegt auf beiden Seiten auf und steht unter Spannung. Schnitte in der richtigen Reihenfolge anklicken.',
        steps: [
          { id: 'crown', label: 'Krone abnehmen', x: 200, y: 236 },
          { id: 'top', label: 'Druckseite anschneiden', x: 300, y: 236 },
          { id: 'bottom', label: 'Zugseite durchtrennen', x: 300, y: 292 },
          { id: 'split', label: 'Stamm teilen', x: 376, y: 236 },
        ],
        order: ['crown', 'top', 'bottom', 'split'],
        wrongText: 'Die Säge klemmt. Der Stamm steht unter Spannung. Keil setzen. (+20 s)',
        wrongPenaltyMs: 20000,
        wrongActionLabel: 'Keil setzen',
        stepDurationMs: 1800,
      },
      hide: ['trunk', 'crown'],
      show: ['log1', 'log2', 'log3'],
      doneText: 'Der Stamm liegt in drei Teilen. Säge aus, Kettenbremse rein.',
    },
    { id: 'clear-log-1', label: 'Stammteil wegräumen', hotspot: 'log1', requires: ['cut-tree'], durationMs: 2000, hide: ['log1'] },
    { id: 'clear-log-2', label: 'Stammteil wegräumen', hotspot: 'log2', requires: ['cut-tree'], durationMs: 2000, hide: ['log2'] },
    { id: 'clear-log-3', label: 'Stammteil wegräumen', hotspot: 'log3', requires: ['cut-tree'], durationMs: 2000, hide: ['log3'] },
    {
      id: 'open-road',
      label: 'Absperrung abbauen, Straße freigeben',
      hotspot: 'road-left',
      requires: ['clear-log-1', 'clear-log-2', 'clear-log-3', 'barrier-left', 'barrier-right'],
      requiresHint: 'Freigeben geht erst, wenn die Straße frei ist und beide Seiten abgesperrt waren.',
      durationMs: 2500,
      hide: ['cone-left', 'cone-right', 'triangle-left'],
      doneText: 'Straße frei. Der PKW-Fahrer winkt und fährt zu seinen Brötchen.',
    },
  ],
};
