import type { MissionDef } from './types';

/** Sturmschaden: Baum liegt quer auf der Landstraße, PKW wartet davor. */
export const STORM_TREE: MissionDef = {
  id: 'storm-tree',
  title: 'Sturmschaden: Baum auf der Straße',
  background: 'storm-tree-bg',
  groundY: 152,
  vehicleHotspot: 'vehicle',
  vehiclePos: { x: 224, y: 160 },
  entryTask: 'exit',
  parTimeMs: 240000,
  reinforcementText: 'Nachalarmierung: zurück zur Unterkunft, GKW holen, wieder anfahren. Die Zeit läuft weiter.',
  hotspots: [
    { id: 'vehicle', label: 'Einsatzfahrzeug', x: 222, y: 104, w: 98, h: 58, walkX: 216, idleText: 'Das Fahrzeug steht sicher am Bankett.' },
    { id: 'car', label: 'Wartender PKW', x: 16, y: 118, w: 60, h: 32, walkX: 80, idleText: 'Der Fahrer hört Radio.' },
    { id: 'tree', label: 'Umgestürzter Baum', x: 86, y: 106, w: 118, h: 42, walkX: 150, idleText: 'Der Stamm liegt quer. Ohne Säge bewegt sich hier nichts.' },
    { id: 'log1', label: 'Stammteil', x: 106, y: 128, w: 30, h: 16, walkX: 121 },
    { id: 'log2', label: 'Stammteil', x: 140, y: 128, w: 30, h: 16, walkX: 155 },
    { id: 'log3', label: 'Stammteil', x: 174, y: 128, w: 30, h: 16, walkX: 189 },
    { id: 'road-left', label: 'Straße, linke Seite', x: 0, y: 120, w: 16, h: 44, walkX: 14, idleText: 'Freie Sicht bis zur Kurve.' },
    { id: 'road-right', label: 'Straße, rechte Seite', x: 204, y: 120, w: 18, h: 44, walkX: 212, idleText: 'Hinter dem Fahrzeug kommt die Kuppe.' },
  ],
  props: [
    { id: 'car', x: 20, y: 130, w: 50, h: 18, color: 'red', label: 'PKW' },
    { id: 'car-blinker', x: 66, y: 134, w: 4, h: 3, color: 'orange' },
    { id: 'crown', x: 84, y: 108, w: 30, h: 40, color: 'green' },
    { id: 'trunk', x: 104, y: 126, w: 100, h: 14, color: 'brown' },
    { id: 'log1', x: 108, y: 132, w: 26, h: 12, color: 'brownLight', hidden: true },
    { id: 'log2', x: 142, y: 132, w: 26, h: 12, color: 'brownLight', hidden: true },
    { id: 'log3', x: 176, y: 132, w: 26, h: 12, color: 'brownLight', hidden: true },
    { id: 'triangle-left', x: 2, y: 140, w: 8, h: 8, color: 'red', hidden: true },
    { id: 'cone-left', x: 10, y: 146, w: 5, h: 8, color: 'orange', hidden: true },
    { id: 'cone-right', x: 210, y: 146, w: 5, h: 8, color: 'orange', hidden: true },
  ],
  tasks: [
    {
      id: 'exit',
      label: 'Aussteigen',
      hotspot: 'vehicle',
      resetOnReturn: true,
      choice: {
        prompt: 'Du sitzt im Fahrzeug. Auf der Landstraße rauscht der Verkehr vorbei.',
        options: [
          { label: 'Verkehr beobachten, dann aussteigen', outcome: 'ok', text: 'Du wartest, bis frei ist, und steigst zur Bankettseite aus.' },
          { label: 'Einfach aussteigen', outcome: 'gameover', text: 'Du bist gestorben, weil du falsch aus dem Auto ausgestiegen bist.' },
        ],
      },
      durationMs: 600,
    },
    {
      id: 'talk-driver',
      label: 'Mit dem Fahrer sprechen',
      hotspot: 'car',
      optional: true,
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Der Fahrer ist unverletzt und bleibt im Auto. Er wollte nur Brötchen holen.',
    },
    {
      id: 'get-barrier',
      label: 'Absperrmaterial holen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['barrier'],
      durationMs: 1500,
      doneText: 'Warndreieck und vier Leitkegel. Reicht für beide Seiten.',
    },
    {
      id: 'barrier-left',
      label: 'Absperrung aufstellen',
      hotspot: 'road-left',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-left', 'triangle-left'],
    },
    {
      id: 'barrier-right',
      label: 'Absperrung aufstellen',
      hotspot: 'road-right',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-right'],
    },
    {
      id: 'ppe',
      label: 'Schnittschutz-PSA anlegen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['ppe'],
      missingEquipmentText: 'Im MTW liegt keine Schnittschutzhose und keine Säge. Der GKW hat beides. Also: absperren, zurück, GKW holen.',
      durationMs: 2000,
      doneText: 'Schnittschutzhose, Helm mit Visier, Gehörschutz. Sitzt.',
    },
    {
      id: 'cut-tree',
      label: 'Baum zerlegen',
      hotspot: 'tree',
      requires: ['exit'],
      equipment: ['chainsaw'],
      missingEquipmentText: 'Keine Kettensäge im MTW. Du kannst absperren, den Baum kriegst du so nicht klein. GKW nachalarmieren.',
      safety: [{ missing: 'ppe', gameOver: 'Du bist gestorben, weil du die Kettensäge ohne Schnittschutz gestartet hast.' }],
      softOrder: [
        { missing: 'barrier-left', penaltyMs: 30000, text: 'Ohne Absperrung rauscht ein Auto an dir vorbei und hupt. Du brichst ab und atmest durch. (+30 s)' },
        { missing: 'barrier-right', penaltyMs: 30000, text: 'Von rechts kommt ein Traktor bis auf zwei Meter ran. Ohne Absperrung ist das nichts. (+30 s)' },
      ],
      usesEquipment: ['chainsaw'],
      minigame: {
        prompt: 'Der Stamm liegt auf beiden Seiten auf und steht unter Spannung. Schnitte in der richtigen Reihenfolge anklicken.',
        steps: [
          { id: 'crown', label: 'Krone abnehmen', x: 100, y: 118 },
          { id: 'top', label: 'Druckseite anschneiden', x: 150, y: 118 },
          { id: 'bottom', label: 'Zugseite durchtrennen', x: 150, y: 146 },
          { id: 'split', label: 'Stamm teilen', x: 188, y: 118 },
        ],
        order: ['crown', 'top', 'bottom', 'split'],
        wrongText: 'Die Säge klemmt. Der Stamm steht unter Spannung. Keil setzen. (+20 s)',
        wrongPenaltyMs: 20000,
        wrongActionLabel: 'Keil setzen',
        stepDurationMs: 1800,
      },
      hide: ['trunk', 'crown'],
      show: ['log1', 'log2', 'log3'],
      doneText: 'Der Stamm liegt in drei Teilen. Säge aus, Kettenbremse rein.',
    },
    { id: 'clear-log-1', label: 'Stammteil wegräumen', hotspot: 'log1', requires: ['cut-tree'], durationMs: 2000, hide: ['log1'] },
    { id: 'clear-log-2', label: 'Stammteil wegräumen', hotspot: 'log2', requires: ['cut-tree'], durationMs: 2000, hide: ['log2'] },
    { id: 'clear-log-3', label: 'Stammteil wegräumen', hotspot: 'log3', requires: ['cut-tree'], durationMs: 2000, hide: ['log3'] },
    {
      id: 'open-road',
      label: 'Absperrung abbauen, Straße freigeben',
      hotspot: 'road-left',
      requires: ['clear-log-1', 'clear-log-2', 'clear-log-3', 'barrier-left', 'barrier-right'],
      requiresHint: 'Freigeben geht erst, wenn die Straße frei ist und beide Seiten abgesperrt waren.',
      durationMs: 2500,
      hide: ['cone-left', 'cone-right', 'triangle-left'],
      doneText: 'Straße frei. Der PKW-Fahrer winkt und fährt zu seinen Brötchen.',
    },
  ],
};
