import type { MissionDef } from './types';

/** Sturmschaden: Baum liegt quer auf der Landstraße, PKW wartet davor. */
export const STORM_TREE: MissionDef = {
  id: 'storm-tree',
  title: 'Sturmschaden: Baum auf der Straße',
  background: 'storm-tree-bg',
  groundY: 608,
  vehicleHotspot: 'vehicle',
  vehiclePos: { x: 828, y: 640 },
  entryTask: 'exit',
  parTimeMs: 240000,
  reinforcementText: 'Nachalarmierung: zurück zur Unterkunft, GKW holen, wieder anfahren. Die Zeit läuft weiter.',
  hotspots: [
    { id: 'vehicle', label: 'Einsatzfahrzeug', x: 824, y: 416, w: 456, h: 232, walkX: 800, idleText: 'Das Fahrzeug steht sicher am Bankett.' },
    { id: 'car', label: 'Wartender PKW', x: 64, y: 472, w: 240, h: 128, walkX: 320, idleText: 'Der Fahrer hört Radio.' },
    { id: 'tree', label: 'Umgestürzter Baum', x: 344, y: 424, w: 392, h: 168, walkX: 600, idleText: 'Der Stamm liegt quer. Ohne Säge bewegt sich hier nichts.' },
    { id: 'log1', label: 'Stammteil', x: 424, y: 512, w: 120, h: 64, walkX: 484 },
    { id: 'log2', label: 'Stammteil', x: 560, y: 512, w: 120, h: 64, walkX: 620 },
    { id: 'log3', label: 'Stammteil', x: 696, y: 512, w: 120, h: 64, walkX: 756 },
    { id: 'road-left', label: 'Straße, linke Seite', x: 0, y: 480, w: 64, h: 176, walkX: 56, idleText: 'Freie Sicht bis zur Kurve.' },
    { id: 'road-right', label: 'Straße, rechte Seite', x: 740, y: 480, w: 80, h: 176, walkX: 776, idleText: 'Hinter dem Fahrzeug kommt die Kuppe.' },
  ],
  props: [
    { id: 'car', x: 80, y: 520, w: 200, h: 72, color: 'red', label: 'PKW' },
    { id: 'car-blinker', x: 264, y: 536, w: 16, h: 12, color: 'orange' },
    { id: 'crown', x: 336, y: 432, w: 120, h: 160, color: 'green' },
    { id: 'trunk', x: 416, y: 504, w: 400, h: 56, color: 'brown' },
    { id: 'log1', x: 432, y: 528, w: 104, h: 48, color: 'brownLight', hidden: true },
    { id: 'log2', x: 568, y: 528, w: 104, h: 48, color: 'brownLight', hidden: true },
    { id: 'log3', x: 704, y: 528, w: 104, h: 48, color: 'brownLight', hidden: true },
    { id: 'triangle-left', x: 8, y: 560, w: 32, h: 32, color: 'red', hidden: true },
    { id: 'cone-left', x: 40, y: 584, w: 20, h: 32, color: 'orange', hidden: true },
    { id: 'cone-right', x: 772, y: 584, w: 20, h: 32, color: 'orange', hidden: true },
  ],
  tasks: [
    {
      id: 'exit',
      label: 'Aussteigen',
      hotspot: 'vehicle',
      resetOnReturn: true,
      choice: {
        prompt: 'Du sitzt im Fahrzeug. Auf der Landstraße rauscht der Verkehr vorbei.',
        options: [
          { label: 'Verkehr beobachten, dann aussteigen', outcome: 'ok', text: 'Du wartest, bis frei ist, und steigst zur Bankettseite aus.' },
          { label: 'Einfach aussteigen', outcome: 'gameover', text: 'Du bist gestorben, weil du falsch aus dem Auto ausgestiegen bist.' },
        ],
      },
      durationMs: 600,
    },
    {
      id: 'talk-driver',
      label: 'Mit dem Fahrer sprechen',
      hotspot: 'car',
      optional: true,
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Der Fahrer ist unverletzt und bleibt im Auto. Er wollte nur Brötchen holen.',
    },
    {
      id: 'get-barrier',
      label: 'Absperrmaterial holen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['barrier'],
      durationMs: 1500,
      doneText: 'Warndreieck und vier Leitkegel. Reicht für beide Seiten.',
    },
    {
      id: 'barrier-left',
      label: 'Absperrung aufstellen',
      hotspot: 'road-left',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-left', 'triangle-left'],
    },
    {
      id: 'barrier-right',
      label: 'Absperrung aufstellen',
      hotspot: 'road-right',
      requires: ['get-barrier'],
      requiresHint: 'Erst Absperrmaterial aus dem Fahrzeug holen.',
      durationMs: 1500,
      show: ['cone-right'],
    },
    {
      id: 'ppe',
      label: 'Schnittschutz-PSA anlegen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['ppe'],
      missingEquipmentText: 'Im MTW liegt keine Schnittschutzhose und keine Säge. Der GKW hat beides. Also: absperren, zurück, GKW holen.',
      durationMs: 2000,
      doneText: 'Schnittschutzhose, Helm mit Visier, Gehörschutz. Sitzt.',
    },
    {
      id: 'cut-tree',
      label: 'Baum zerlegen',
      hotspot: 'tree',
      requires: ['exit'],
      equipment: ['chainsaw'],
      missingEquipmentText: 'Keine Kettensäge im MTW. Du kannst absperren, den Baum kriegst du so nicht klein. GKW nachalarmieren.',
      safety: [{ missing: 'ppe', gameOver: 'Du bist gestorben, weil du die Kettensäge ohne Schnittschutz gestartet hast.' }],
      softOrder: [
        { missing: 'barrier-left', penaltyMs: 30000, text: 'Ohne Absperrung rauscht ein Auto an dir vorbei und hupt. Du brichst ab und atmest durch. (+30 s)' },
        { missing: 'barrier-right', penaltyMs: 30000, text: 'Von rechts kommt ein Traktor bis auf zwei Meter ran. Ohne Absperrung ist das nichts. (+30 s)' },
      ],
      usesEquipment: ['chainsaw'],
      minigame: {
        prompt: 'Der Stamm liegt auf beiden Seiten auf und steht unter Spannung. Schnitte in der richtigen Reihenfolge anklicken.',
        steps: [
          { id: 'crown', label: 'Krone abnehmen', x: 400, y: 472 },
          { id: 'top', label: 'Druckseite anschneiden', x: 600, y: 472 },
          { id: 'bottom', label: 'Zugseite durchtrennen', x: 600, y: 584 },
          { id: 'split', label: 'Stamm teilen', x: 752, y: 472 },
        ],
        order: ['crown', 'top', 'bottom', 'split'],
        wrongText: 'Die Säge klemmt. Der Stamm steht unter Spannung. Keil setzen. (+20 s)',
        wrongPenaltyMs: 20000,
        wrongActionLabel: 'Keil setzen',
        stepDurationMs: 1800,
      },
      hide: ['trunk', 'crown'],
      show: ['log1', 'log2', 'log3'],
      doneText: 'Der Stamm liegt in drei Teilen. Säge aus, Kettenbremse rein.',
    },
    { id: 'clear-log-1', label: 'Stammteil wegräumen', hotspot: 'log1', requires: ['cut-tree'], durationMs: 2000, hide: ['log1'] },
    { id: 'clear-log-2', label: 'Stammteil wegräumen', hotspot: 'log2', requires: ['cut-tree'], durationMs: 2000, hide: ['log2'] },
    { id: 'clear-log-3', label: 'Stammteil wegräumen', hotspot: 'log3', requires: ['cut-tree'], durationMs: 2000, hide: ['log3'] },
    {
      id: 'open-road',
      label: 'Absperrung abbauen, Straße freigeben',
      hotspot: 'road-left',
      requires: ['clear-log-1', 'clear-log-2', 'clear-log-3', 'barrier-left', 'barrier-right'],
      requiresHint: 'Freigeben geht erst, wenn die Straße frei ist und beide Seiten abgesperrt waren.',
      durationMs: 2500,
      hide: ['cone-left', 'cone-right', 'triangle-left'],
      doneText: 'Straße frei. Der PKW-Fahrer winkt und fährt zu seinen Brötchen.',
    },
  ],
};
