import type { MissionDef } from './types';

/** Wasserschaden: Keller eines Mehrfamilienhauses vollgelaufen, Strom liegt noch an. */
export const WATER_BASEMENT: MissionDef = {
  id: 'water-basement',
  title: 'Wasserschaden: Keller vollgelaufen',
  background: 'water-basement-bg',
  groundY: 316,
  vehicleHotspot: 'vehicle',
  vehiclePos: { x: 414, y: 356 },
  entryTask: 'exit',
  parTimeMs: 240000,
  reinforcementText: 'Nachalarmierung: zurück zur Unterkunft, GKW holen, wieder anfahren. Die Zeit läuft weiter.',
  hotspots: [
    { id: 'vehicle', label: 'Einsatzfahrzeug', x: 412, y: 252, w: 228, h: 108, walkX: 400, idleText: 'Das Fahrzeug steht am Straßenrand, Warnblinker an.' },
    { id: 'stairs', label: 'Kellertreppe', x: 44, y: 272, w: 128, h: 88, walkX: 184, idleText: 'Unten plätschert es.' },
    { id: 'fusebox', label: 'Sicherungskasten', x: 260, y: 200, w: 32, h: 48, walkX: 276, idleText: 'Hauptschalter. Steht auf AUS.' },
    { id: 'door', label: 'Haustür', x: 196, y: 188, w: 60, h: 80, walkX: 226, idleText: 'Die Bewohner warten oben.' },
    { id: 'gully', label: 'Gully', x: 350, y: 304, w: 52, h: 28, walkX: 340, idleText: 'Der Gully schluckt, was kommt.' },
  ],
  props: [
    { id: 'water', x: 52, y: 320, w: 112, h: 36, color: 'water' },
    { id: 'pump', x: 124, y: 296, w: 24, h: 18, color: 'grayLight', hidden: true },
    { id: 'hose1', x: 148, y: 304, w: 80, h: 6, color: 'red', hidden: true },
    { id: 'hose2', x: 228, y: 304, w: 76, h: 6, color: 'red', hidden: true },
    { id: 'hose3', x: 304, y: 304, w: 66, h: 6, color: 'red', hidden: true },
  ],
  tasks: [
    {
      id: 'exit',
      label: 'Aussteigen',
      hotspot: 'vehicle',
      resetOnReturn: true,
      choice: {
        prompt: 'Du stehst in der Ringstraße. Wohngebiet, aber Lieferverkehr.',
        options: [
          { label: 'Kurz schauen, dann aussteigen', outcome: 'ok', text: 'Ein Lieferwagen rollt vorbei. Dann ist frei.' },
          { label: 'Einfach aussteigen', outcome: 'penalty', penaltyMs: 15000, text: 'Der Lieferwagen bremst scharf und hupt. Glück gehabt. Das kostet Nerven und Zeit. (+15 s)' },
        ],
      },
      durationMs: 600,
    },
    {
      id: 'recon',
      label: 'Lage erkunden',
      hotspot: 'stairs',
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Wasser steht etwa kniehoch, es riecht nach Heizöl. Und da brummt was: Im Keller liegt noch Strom auf der Leitung.',
    },
    {
      id: 'power-off',
      label: 'Strom abschalten',
      hotspot: 'fusebox',
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Hauptschalter aus. Das Brummen hört auf.',
    },
    {
      id: 'talk-residents',
      label: 'Bewohner informieren',
      hotspot: 'door',
      optional: true,
      requires: ['exit'],
      durationMs: 1500,
      doneText: 'Die Bewohner bleiben oben. Frau Weber bringt später Kaffee.',
    },
    {
      id: 'get-pump',
      label: 'Pumpe und Schläuche holen',
      hotspot: 'vehicle',
      requires: ['exit'],
      equipment: ['pump', 'hose'],
      missingEquipmentText: 'Im MTW liegt keine Pumpe und kein Schlauch. Das kann nur der GKW. Erkunden, Strom aus, dann GKW holen.',
      durationMs: 2000,
      doneText: 'Tauchpumpe, drei Schläuche, Stromerzeuger. Schwer.',
    },
    {
      id: 'place-pump',
      label: 'Pumpe an der Kellertreppe aufstellen',
      hotspot: 'stairs',
      requires: ['get-pump', 'recon'],
      requiresHint: 'Erst Lage erkunden und die Pumpe aus dem Fahrzeug holen.',
      safety: [{ missing: 'power-off', gameOver: 'Du bist gestorben, weil du mit der Pumpe in den Keller gestiegen bist, während noch Strom auf der Leitung lag.' }],
      durationMs: 2500,
      show: ['pump'],
      doneText: 'Pumpe steht auf der untersten trockenen Stufe. Jetzt die Leitung.',
    },
    {
      id: 'hose',
      label: 'Schlauchleitung zum Gully legen',
      hotspot: 'gully',
      requires: ['place-pump'],
      requiresHint: 'Ohne Pumpe keine Leitung.',
      equipment: ['hose'],
      minigame: {
        prompt: 'Drei Schlauchsegmente von der Pumpe bis zum Gully. Kupplungen in der richtigen Reihenfolge anklicken.',
        steps: [
          { id: 'pump-out', label: 'Pumpenausgang', x: 148, y: 292 },
          { id: 'c1', label: 'Kupplung 1', x: 228, y: 292 },
          { id: 'c2', label: 'Kupplung 2', x: 304, y: 292 },
          { id: 'gully', label: 'Gully-Einlauf', x: 376, y: 300 },
        ],
        order: ['pump-out', 'c1', 'c2', 'gully'],
        wrongText: 'Die Kupplung passt nicht. Von der Pumpe aus arbeiten, sonst hängt am Ende ein Stück in der Luft. (+15 s)',
        wrongPenaltyMs: 15000,
        wrongActionLabel: 'Kupplung lösen',
        stepDurationMs: 1200,
      },
      show: ['hose1', 'hose2', 'hose3'],
      doneText: 'Leitung liegt, Kupplungen dicht.',
    },
    {
      id: 'pump-run',
      label: 'Pumpe starten',
      hotspot: 'stairs',
      requires: ['hose'],
      requiresHint: 'Erst die Schlauchleitung zum Gully legen.',
      usesEquipment: ['pump'],
      durationMs: 20000,
      progressLabel: 'Pumpe läuft',
      tween: { prop: 'water', h: 6, y: 350 },
      doneText: 'Der Wasserstand ist unten. Restwasser steht in den Ecken.',
    },
    {
      id: 'wet-vac',
      label: 'Nachpumpen mit dem Wassersauger',
      hotspot: 'stairs',
      optional: true,
      requires: ['pump-run'],
      equipment: ['wet-vac'],
      usesEquipment: ['wet-vac'],
      durationMs: 5000,
      hide: ['water'],
      doneText: 'Keller trocken bis auf Pfützen. Mehr geht nicht ohne Trocknungsgerät.',
    },
    {
      id: 'pack-up',
      label: 'Gerät zurück ins Fahrzeug',
      hotspot: 'vehicle',
      requires: ['pump-run'],
      requiresHint: 'Erst pumpen, dann einpacken.',
      durationMs: 3000,
      hide: ['pump', 'hose1', 'hose2', 'hose3'],
      doneText: 'Alles verladen. Strom bleibt aus, bis der Elektriker da war. Das sagst du den Bewohnern noch.',
    },
  ],
};
